CREATE TABLE USER
(
    ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(100) UNIQUE NOT NULL,
    SALT     TINYBLOB            NOT NULL,
    PASSWORD VARCHAR(1000)       NOT NULL
);

CREATE TABLE PERSONAL
(
    ID            INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID       INTEGER NOT NULL UNIQUE,
    NAME          VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ROLE          INTEGER default 3,
    PERMISSIONS   INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

CREATE TABLE BOOK
(
    ID      INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER,
    TITLE   VARCHAR(100),
    AUTHOR  VARCHAR(100),
    GENRE   INTEGER,
    MIN_AGE INTEGER default 0,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID)
)